import type { ElementType } from "react";
import {
  SiPython,
  SiR,
  SiFastapi,
  SiStreamlit,
  SiScikitlearn,
  SiTensorflow,
  SiPytorch,
  SiMeta,
  SiMistralai,
  SiLangchain,
  SiHuggingface,
  SiOllama,
  SiOpencv,
  SiRoboflow,
  SiApachespark,
  SiAirbyte,
  SiApachekafka,
  SiApacheairflow,
  SiMlflow,
  SiDocker,
  SiKubernetes,
  SiMetabase,
  SiApachesuperset,
  SiLooker,
  SiGooglecloud,
  SiOvh,
  SiLinux,
} from "react-icons/si";
import { FaAws } from "react-icons/fa6";
import { Database, Layers, Gauge, Bot, Mic, Library, Cloud, Wrench, ScanEye, ShieldCheck, Languages, BarChart3 } from "lucide-react";

export const techIcons: Record<string, ElementType> = {
  Python: SiPython,
  R: SiR,
  SQL: Database,
  FastAPI: SiFastapi,
  Streamlit: SiStreamlit,
  "scikit-learn": SiScikitlearn,
  XGBoost: Layers,
  LightGBM: Gauge,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  "OpenAI API": Bot,
  "Meta LLaMA 3": SiMeta,
  "Mistral AI": SiMistralai,
  LangChain: SiLangchain,
  LlamaIndex: Library,
  HuggingFace: SiHuggingface,
  Ollama: SiOllama,
  OpenCV: SiOpencv,
  "YOLO v8/v9": ScanEye,
  "TensorFlow Lite": SiTensorflow,
  Roboflow: SiRoboflow,
  Whisper: Mic,
  Masakhane: Languages,
  AfroNLP: Languages,
  "Apache Spark": SiApachespark,
  dbt: Wrench,
  Airbyte: SiAirbyte,
  "Apache Kafka": SiApachekafka,
  Airflow: SiApacheairflow,
  MLflow: SiMlflow,
  "Evidently AI": ShieldCheck,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  "Power BI": BarChart3,
  Metabase: SiMetabase,
  "Apache Superset": SiApachesuperset,
  "Looker Studio": SiLooker,
  AWS: FaAws,
  "Google Cloud": SiGooglecloud,
  Azure: Cloud,
  OVH: SiOvh,
  "On-premise Linux": SiLinux,
};
