import type { ElementType } from "react";
import {
  SiPython,
  SiR,
  SiFastapi,
  SiStreamlit,
  SiScikitlearn,
  SiTensorflow,
  SiPytorch,
  SiMeta,
  SiMistralai,
  SiLangchain,
  SiHuggingface,
  SiOllama,
  SiOpencv,
  SiRoboflow,
  SiApachespark,
  SiAirbyte,
  SiApachekafka,
  SiApacheairflow,
  SiMlflow,
  SiDocker,
  SiKubernetes,
  SiMetabase,
  SiApachesuperset,
  SiLooker,
  SiGooglecloud,
  SiOvh,
  SiLinux,
} from "react-icons/si";
import { FaAws } from "react-icons/fa6";
import { Database, Layers, Gauge, Bot, Mic, Library, Cloud, Wrench, ScanEye, ShieldCheck, Languages, BarChart3 } from "lucide-react";

export const techIcons: Record<string, ElementType> = {
  Python: SiPython,
  R: SiR,
  SQL: Database,
  FastAPI: SiFastapi,
  Streamlit: SiStreamlit,
  "scikit-learn": SiScikitlearn,
  XGBoost: Layers,
  LightGBM: Gauge,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  "OpenAI API": Bot,
  "Meta LLaMA 3": SiMeta,
  "Mistral AI": SiMistralai,
  LangChain: SiLangchain,
  LlamaIndex: Library,
  HuggingFace: SiHuggingface,
  Ollama: SiOllama,
  OpenCV: SiOpencv,
  "YOLO v8/v9": ScanEye,
  "TensorFlow Lite": SiTensorflow,
  Roboflow: SiRoboflow,
  Whisper: Mic,
  Masakhane: Languages,
  AfroNLP: Languages,
  "Apache Spark": SiApachespark,
  dbt: Wrench,
  Airbyte: SiAirbyte,
  "Apache Kafka": SiApachekafka,
  Airflow: SiApacheairflow,
  MLflow: SiMlflow,
  "Evidently AI": ShieldCheck,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  "Power BI": BarChart3,
  Metabase: SiMetabase,
  "Apache Superset": SiApachesuperset,
  "Looker Studio": SiLooker,
  AWS: FaAws,
  "Google Cloud": SiGooglecloud,
  Azure: Cloud,
  OVH: SiOvh,
  "On-premise Linux": SiLinux,
};

const NEUTRAL = "var(--color-navy)";

export const techColors: Record<string, string> = {
  Python: "#3776AB",
  R: "#276DC3",
  SQL: NEUTRAL,
  FastAPI: "#009688",
  Streamlit: "#FF4B4B",
  "scikit-learn": "#F7931E",
  XGBoost: NEUTRAL,
  LightGBM: NEUTRAL,
  TensorFlow: "#FF6F00",
  PyTorch: "#EE4C2C",
  "OpenAI API": NEUTRAL,
  "Meta LLaMA 3": "#0467DF",
  "Mistral AI": "#FA520F",
  LangChain: "#7FC8FF",
  LlamaIndex: NEUTRAL,
  HuggingFace: "#FFD21E",
  Ollama: "#000000",
  OpenCV: "#5C3EE8",
  "YOLO v8/v9": NEUTRAL,
  "TensorFlow Lite": "#FF6F00",
  Roboflow: "#6706CE",
  Whisper: NEUTRAL,
  Masakhane: NEUTRAL,
  AfroNLP: NEUTRAL,
  "Apache Spark": "#E25A1C",
  dbt: "#FF694B",
  Airbyte: "#615EFF",
  "Apache Kafka": "#231F20",
  Airflow: "#017CEE",
  MLflow: "#0194E2",
  "Evidently AI": NEUTRAL,
  Docker: "#2496ED",
  Kubernetes: "#326CE5",
  "Power BI": "#F2C811",
  Metabase: "#509EE3",
  "Apache Superset": "#20A6C9",
  "Looker Studio": "#4285F4",
  AWS: "#FF9900",
  "Google Cloud": "#4285F4",
  Azure: "#0078D4",
  OVH: "#123F6D",
  "On-premise Linux": "#FCC624",
};
